// @ts-nocheck
import { browser } from 'fumadocs-mdx/runtime/browser';
import type * as Config from '../source.config';

const create = browser<typeof Config, import("fumadocs-mdx/runtime/types").InternalTypeConfig & {
  DocData: {
  }
}>();
const browserCollections = {
  docs: create.doc("docs", {"api-reference.de.mdx": () => import("../content/docs/api-reference.de.mdx?collection=docs"), "api-reference.es.mdx": () => import("../content/docs/api-reference.es.mdx?collection=docs"), "api-reference.fr.mdx": () => import("../content/docs/api-reference.fr.mdx?collection=docs"), "api-reference.ja.mdx": () => import("../content/docs/api-reference.ja.mdx?collection=docs"), "api-reference.ko.mdx": () => import("../content/docs/api-reference.ko.mdx?collection=docs"), "api-reference.mdx": () => import("../content/docs/api-reference.mdx?collection=docs"), "faq.de.mdx": () => import("../content/docs/faq.de.mdx?collection=docs"), "faq.es.mdx": () => import("../content/docs/faq.es.mdx?collection=docs"), "faq.fr.mdx": () => import("../content/docs/faq.fr.mdx?collection=docs"), "faq.ja.mdx": () => import("../content/docs/faq.ja.mdx?collection=docs"), "faq.ko.mdx": () => import("../content/docs/faq.ko.mdx?collection=docs"), "faq.mdx": () => import("../content/docs/faq.mdx?collection=docs"), "getting-started.de.mdx": () => import("../content/docs/getting-started.de.mdx?collection=docs"), "getting-started.es.mdx": () => import("../content/docs/getting-started.es.mdx?collection=docs"), "getting-started.fr.mdx": () => import("../content/docs/getting-started.fr.mdx?collection=docs"), "getting-started.ja.mdx": () => import("../content/docs/getting-started.ja.mdx?collection=docs"), "getting-started.ko.mdx": () => import("../content/docs/getting-started.ko.mdx?collection=docs"), "getting-started.mdx": () => import("../content/docs/getting-started.mdx?collection=docs"), "getting-started.zh-CN.mdx": () => import("../content/docs/getting-started.zh-CN.mdx?collection=docs"), "index.de.mdx": () => import("../content/docs/index.de.mdx?collection=docs"), "index.es.mdx": () => import("../content/docs/index.es.mdx?collection=docs"), "index.fr.mdx": () => import("../content/docs/index.fr.mdx?collection=docs"), "index.ja.mdx": () => import("../content/docs/index.ja.mdx?collection=docs"), "index.ko.mdx": () => import("../content/docs/index.ko.mdx?collection=docs"), "index.mdx": () => import("../content/docs/index.mdx?collection=docs"), "index.zh-CN.mdx": () => import("../content/docs/index.zh-CN.mdx?collection=docs"), }),
};
export default browserCollections;